extends Domain_Data
class_name Element_Data


# Damage Multiplier affects type of damage dictacted by interaction type drop-down. REFLECT, TITHE and REGEN use an optional self_damage and  value for damage/healing received. ABSORB makes all damage inflicted into healing instead, and SUSTAIN makes the element deals damage over time. In SUSTAIN, set the durarion value and interval values to non-zero values, and make sure interval is lower than duration (preferably less than half).

# self_damage should have a 'gauge' String variable to indicate which gauge is being damaged by TITHE, and which gauge is regenerated by REGEN.
#multiplier needs to be changed to a float.
# Groups need to be reorganized so that we don't need to use Dictionaries.


@export_group("Intensity")
@export var BASS: Element_Interaction_Data
@export var TREBLE: Element_Interaction_Data
@export var STRETCHED: Element_Interaction_Data
@export var COMPRESSED: Element_Interaction_Data
@export var HEAT: Element_Interaction_Data
@export var CHILL: Element_Interaction_Data
@export var SIMPLE: Element_Interaction_Data
@export var COMPLEX: Element_Interaction_Data

@export_group("Transfer")
@export var CONDUCTIVE: Element_Interaction_Data
@export var MAGNETIC: Element_Interaction_Data
@export var PULSE: Element_Interaction_Data
@export var REFLECTIVE: Element_Interaction_Data
@export var RADIANT: Element_Interaction_Data
@export var VOID: Element_Interaction_Data
@export var PLASMA: Element_Interaction_Data
@export var MASSIVE: Element_Interaction_Data
@export var QUANTUM: Element_Interaction_Data
@export var ELECTRONIC: Element_Interaction_Data
@export var SOLVENT: Element_Interaction_Data
@export var OXIDIZING: Element_Interaction_Data
@export var PARTICLE: Element_Interaction_Data

@export_group("Virtual")
@export var LIMIT: Element_Interaction_Data
@export var VECTOR: Element_Interaction_Data
@export var MATRIX: Element_Interaction_Data
@export var DATA: Element_Interaction_Data
@export var BINARY: Element_Interaction_Data
@export var MEMORY: Element_Interaction_Data
@export var GENETIC: Element_Interaction_Data
@export var ILLUSION:Element_Interaction_Data

@export_group("Minerals")
@export var OBSIDIAN: Element_Interaction_Data
@export var STEAM: Element_Interaction_Data
@export var SMOKE: Element_Interaction_Data
@export var PLASTIC: Element_Interaction_Data
@export var GLASS: Element_Interaction_Data
@export var LIQUID: Element_Interaction_Data
@export var GEL:Element_Interaction_Data
@export var NEON:Element_Interaction_Data
@export var METAL:Element_Interaction_Data
@export var CRYSTAL: Element_Interaction_Data
@export var  DIAMOND: Element_Interaction_Data

@export_group("Patterns")
@export var GRADIENT: Element_Interaction_Data
@export var RAINBOW: Element_Interaction_Data
@export var CHROMATIC: Element_Interaction_Data
@export var PRISMATIC: Element_Interaction_Data
@export var FRACTAL: Element_Interaction_Data
@export var ORDERED: Element_Interaction_Data
@export var CHAOTIC: Element_Interaction_Data
